config/routes.rb
Prospectingzen::Application.routes.draw do

  resources :charges
  
  devise_for :users

  devise_scope :user do
  authenticated :user do
    root 'pages#home', as: :authenticated_root
    get 'feedback' => 'pages#feedback'
    get 'referrals' => 'pages#referrals'
    get 'landing' => 'pages#landing'
    resources :events, :contacts, :leadgens
    get 'assistants' => 'pages#assistants'

  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  

end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :user

	has_attached_file :spreadsheet, :default_url => "http://simpleicon.com/wp-content/uploads/paperclip.png"
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @events = Event.all
    @events = Event.all.order("deadline ASC")
  end

  def show
  end

  def new
    @event = current_user.events.build
  end

  def edit
  end

  def create
    @event = current_user.events.build(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event }
      else
        format.html { render action: 'new' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url }
      format.json { head :no_content }
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def correct_user 
      @event = current_user.events.find_by(id: params[:id])
      redirect_to events_path if @event.nil?
    end  

    def event_params
      params.require(:event).permit(:eventname, :eventlocation, :eventdate, :eventnotes, :deadline, :spreadsheet)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_events.html.erb
<% @events.each do |event| %>
  		<p><%= link_to "#{event.eventname}, #{event.eventlocation}", event %>
  			<span class="small">
  				<%= "#{event.deadline}" %>
  				<!-- | <%= link_to 'Edit', edit_event_path(event) %>-->
  			</span>
  		</p>
  		<hr style="margin-top:-20px">
 <% end %>

app/views/events/_form.html.erb
<%= simple_form_for @event, html: {multipart: true} do |f| %>
  <%= f.error_notification %>

  <div class="form-group">
    <%= f.input :eventname, :label => "Event Name" %>
    <%= f.input :eventlocation, :label => "Location of the Event" %>
    <%= f.input :eventdate, :label => "Date of the Event" %>
    <%= f.input :eventnotes, :label => "Any notes about the Event" %>
    <%= f.input :deadline, :label => "Assignment Deadline" %>



  </div>

<!--  <div class="form-group">
    <%= f.label :spreadsheet %>
    <%= f.file_field :image, class: "form-control" %>
  </div>-->

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <br />
<% end %>

app/views/events/edit.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">
		<h3>Edit your event information</h3>

<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |

</div>

app/views/events/index.html.erb
<%= render 'layouts/nav_sheets' %>

<div class="content-events">
    <h1 style="margin:25px 0 60px 0">My Events <span style="float:right"><%= link_to 'New Event', new_event_path, class: "button" %></span></h1>

      <p>Your assistant will use this information to find prospectects who are attending this event.</p>

      <%= render 'events' %>
<br>
</div>
</div>

app/views/events/new.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">
		<h3>Enter your event information</h3>

			<p>Your assistant will take this and find the contacts attending this event.</p>

<%= render 'form' %>


</div>

app/views/events/show.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">

<div class="contact-card">

<p>
  <strong>Event Name:</strong>
  <%= @event.eventname %>
</p>

<p>
  <strong>Event Location:</strong>
  <%= @event.eventlocation %>
</p>

<p>
  <strong>Event Date:</strong>
  <%= @event.eventdate %>
</p>

<p>
  <strong>Event Notes:</strong>
  <%= @event.eventnotes %>
</p>

</div>

<p>
  <strong>Assignment Deadline:</strong>
  <%= @event.deadline %>
</p>

<% if @event.user == current_user %>
<%= link_to 'Edit', edit_event_path(@event) %> |  <%= link_to 'Delete', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>

</div>