config/routes.rb
Prospectingzen::Application.routes.draw do

  resources :charges
  
  devise_for :users

  devise_scope :user do
  authenticated :user do
    root 'pages#home', as: :authenticated_root
    get 'feedback' => 'pages#feedback'
    get 'referrals' => 'pages#referrals'
    get 'landing' => 'pages#landing'
    resources :events, :contacts, :leadgens
    get 'assistants' => 'pages#assistants'

  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  

end

app/views/pages/assistants.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">
		<h1 style="margin:25px 0">Stream of Assignments</h1>

<div class="stream-container">
	
	<h6 style="float:left">Lead Generation Campaigns</h6><h4 style="float:right">Deadline</h4>
		<br />
		<div>
			<%= render 'leadgens/leadgen' %>
		</div>
</div>	

<div class="stream-container">
		<h6 style="float:left">Latest Events</h6><h4 style="float:right">Deadline</h4>
		<br />
		<div>
			<%= render 'events/events' %>
		</div>
</div>

<div class="stream-container">
	<h6 style="float:left">VIP Contacts</h6><h4 style="float:right">Deadline</h4>
		<br />
		<div>
			<%= render 'contacts/contacts' %>
		</div>
</div>

<!-- close container div -->
</div>   

app/views/pages/feedback.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-referalls">
<h2>Assistant Feedback</h2>
<p>How would you rate the work your assistant is producing?</p>
<div class="rating">
    <span><input type="radio" name="rating" id="str5" value="5"><label for="str5"></label></span>
    <span><input type="radio" name="rating" id="str4" value="4"><label for="str4"></label></span>
    <span><input type="radio" name="rating" id="str3" value="3"><label for="str3"></label></span>
    <span><input type="radio" name="rating" id="str2" value="2"><label for="str2"></label></span>
    <span><input type="radio" name="rating" id="str1" value="1"><label for="str1"></label></span>
</div>

<textarea col="5" rows="2" placeholder="Why did you choose that rating? What can they do better?">
</textarea>

<div class="divider"></div>

<h2>Product Feedback</h2>
<p>How would you rate this product?</p>
<div class="rating">
    <span><input type="radio" name="rating" id="strP1" value="5"><label for="strP5"></label></span>
    <span><input type="radio" name="rating" id="strP2" value="4"><label for="strP4"></label></span>
    <span><input type="radio" name="rating" id="strP3" value="3"><label for="strP3"></label></span>
    <span><input type="radio" name="rating" id="strP4" value="2"><label for="strP2"></label></span>
    <span><input type="radio" name="rating" id="strP5" value="1"><label for="strP1"></label></span>
</div>

<textarea col="5" rows="2" placeholder="How can we make it better?">
</textarea>

<div class="button-area">
<button value="Sumbit">Submit</button>
</div>
</div>

app/views/pages/home.html.erb
<% if user_signed_in? %>
<%= render 'layouts/nav_sheets' %>
<div class="content-sheets">

<p>Give your assistant a task and check back after you've gotten the email notifying you that they have finished.</p><hr>

		<p class="center"><%= link_to 'Generate Leads', new_leadgen_path, class: "button" %>&nbsp;&nbsp;&nbsp;<%= link_to 'VIP Contact', new_contact_path, class: "button" %>&nbsp;&nbsp;&nbsp;<%= link_to 'Add New Event', new_event_path, class: "button" %></p> 

		<blockquote>
		<%= link_to new_leadgen_path do %><h4>Generate Leads</h4><% end %>
		Build your sales funnel by passing over a list of the companies you're targeting. Your assistant will find detailed contact information for the right stakeholders.
		</blockquote>
 
	<blockquote>
		<%= link_to new_contact_path do %><h4>VIP Contacts</h4><% end %>
	Already know the name of someone important? Your freelancer will find out the rest of their contact information and create a contact card complete with their social accounts, birthday, address, and more.</blockquote>


		<blockquote>
		<%= link_to new_event_path do %><h4>Event Information</h4><% end %>
	Provide your assistant with information about upcoming events so they can build a list of leads.</blockquote>

</div>

<!-- close container div -->
</div>   

<% else %>
<%= render 'layouts/loginheader' %>
<%= link_to "Login", new_user_session_path %>
<% end %>

app/views/pages/landing.html.erb
<%= link_to "Sign up!", new_user_registration_path %>
<% if user_signed_in? %>
<%= link_to "Edit Profile", edit_user_registration_path %>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
                      <% else %>
<%= link_to "Login", new_user_session_path %>
                      <% end %>

app/views/pages/landing_unused.html.erb
<%= link_to "Sign up!", new_user_registration_path %>
<% if user_signed_in? %>
<%= link_to "Edit Profile", edit_user_registration_path %>
<%= link_to "Logout", destroy_user_session_path, method: :delete %>
                      <% else %>
<%= link_to "Login", new_user_session_path %>
                      <% end %>

app/views/pages/referrals.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-referalls">
	<blockquote>
		<h3>Your referral link is <a href="http://prospectingzen.co/abcd1234">prospectingzen.co/abcd1234</a></h3></blockquote>

			<p>When someone clicks your link and signs up as a new customer for ProspectingZen (and keeps it for 3 months) you’ll receive a credit equal to one month fee. As a bonus, anyone who signs up from your referral link will also get their first month free.</p>

			<p>There is no limit to the number of customers you can refer, feel free to button your link with as many people as you think may benefit from the service. Happy prospecting!</p>
	<blockquote>
		<p>Hey there,</p>
		<p>I've been using ProspectingZen to generate new sales prospects and thought you would find it useful as well. If you sign up with <a href="http://prospectingzen.co/abcd1234">this referral link</a>, you'll get a free month using the service.</p>
			<a href="http://prospectingzen.co/abcd1234">prospectingzen.co/abcd1234</a></p>
	</blockquote>
<!--<p>Average number of customers referred by existing customers: 3</p>-->
</div>
<!-- close container div -->
</div>   

app/views/pages/sheets.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-sheets">
    <div id="example1" class="handsontable"></div>
</div>

<!-- close container div -->
</div>   