config/routes.rb
Prospectingzen::Application.routes.draw do

  resources :charges
  
  devise_for :users

  devise_scope :user do
  authenticated :user do
    root 'pages#home', as: :authenticated_root
    get 'feedback' => 'pages#feedback'
    get 'referrals' => 'pages#referrals'
    get 'landing' => 'pages#landing'
    resources :events, :contacts, :leadgens
    get 'assistants' => 'pages#assistants'

  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  

end

app/models/leadgen.rb
class Leadgen < ActiveRecord::Base
	belongs_to :user

	has_attached_file :leadgensheet
	validates_attachment_content_type :leadgensheet, :content_type => [ 'text/csv','text/comma-separated-values','text/csv','application/csv','application/excel','application/vnd.ms-excel','application/vnd.msexcel','text/anytext','text/plain' ], :message => 'file must be a .csv' 
	has_many :leadgensheet

	serialize :seniority, Array
end

app/controllers/leadgens_controller.rb
class LeadgensController < ApplicationController
  before_action :set_leadgen, only: [:show, :edit, :update, :destroy]


  # GET /leadgens
  # GET /leadgens.json
  def index
    @leadgens = Leadgen.all
    @leadgens = Leadgen.all.order("deadline ASC")
  end

  # GET /leadgens/1
  # GET /leadgens/1.json
  def show
    @leadgens = Leadgen.all
  end

  # GET /leadgens/new
  def new
    @leadgen = Leadgen.new
    tag_ids = params[:tag_ids]
  end

  # GET /leadgens/1/edit
  def edit
    tag_ids = params[:tag_ids]
  end

  # POST /leadgens
  # POST /leadgens.json
  def create
    @leadgen = Leadgen.new(leadgen_params)

    respond_to do |format|
      if @leadgen.save
        format.html { redirect_to @leadgen, notice: 'Leadgen was successfully created.' }
        format.json { render action: 'show', status: :created, location: @leadgen }
      else
        format.html { render action: 'new' }
        format.json { render json: @leadgen.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /leadgens/1
  # PATCH/PUT /leadgens/1.json
  def update
    respond_to do |format|
      if @leadgen.update(leadgen_params)
        format.html { redirect_to @leadgen, notice: 'Leadgen was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @leadgen.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leadgens/1
  # DELETE /leadgens/1.json
  def destroy
    @leadgen.destroy
    respond_to do |format|
      format.html { redirect_to leadgens_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to button common setup or constraints between actions.
    def set_leadgen
      @leadgen = Leadgen.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def leadgen_params
      params.require(:leadgen).permit(:companies, :deadline, :leadsper, :title, :leadgensheet, :seniority => [])
    end
end

app/helpers/leadgens_helper.rb
module LeadgensHelper
end

app/views/leadgens/_form.html.erb
<%= simple_form_for @leadgen, html: {multipart: true} do |f| %>
  <%= f.error_notification %>
	<div class="deadline">
	<%= f.input :deadline, :as => "date", :label =>"Freelancer deadline for this assignment" %>
</div>
<hr>
  <div class="form-inputs">
    <%= f.input :title, :label => "Title of this lead generation campaign", :placeholder => "What should we call this assignment?" %>
    <%= f.input :seniority, :as => :check_boxes, :label => "Select the seniority levels of the prospects you're targeting", :collection => [ "C-Level Excecutive", "Vice President", "Director", "Senior", "Manager", "Owner", "Partner" ], :include_hidden => false %>



    <%= f.input :companies, :input_html => { :rows => 8, :placeholder => "Please separate each company with a comma." } %>

    <%= f.input :leadsper, :label => "Number of leads per company", :placeholder => "How many leads should your freelancer find per company?" %>
  </div>

<% if current_page?(new_leadgen_path) %> 
  <div class="form-actions">
    <%= f.button :submit, :value => "Generate leads" %>
  </div>
<% else %>
<div class="form-actions">
    <%= f.button :submit, :value => "Update assignment" %>
  </div>       
<% end %> 

<% end %>

app/views/leadgens/_leadgen.html.erb
<% @leadgens.each do |leadgen| %>
	<p><%= link_to "#{leadgen.title}", leadgen %>
 		<span class="small">
 			<%= "#{leadgen.deadline}" %>
 			<!-- | 
 			<%= link_to 'Edit', edit_leadgen_path(leadgen) %>-->
		</span>
	</p>
	<hr style="margin-top:-20px">
<% end %>	

app/views/leadgens/_leadgenupload.html.erb
<%= simple_form_for @leadgen, html: { multipart: true } do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs">
    <p style="margin:5px 0;">Upload Spreedsheet</p>
    <%= f.file_field :leadgensheet, :label => "Upload Spreadsheet" %>
  </div>

  <div class="form-actions upload-sheets">
    <%= f.button :submit, :value => "Confirm Upload" %>
  </div>     

  <p><%= link_to "#{@leadgen.leadgensheet_file_name}", @leadgen.leadgensheet.url  %>
  </p>
  <hr style="margin-top:-20px">

<% end %>

app/views/leadgens/edit.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">

<h3>Enter the list of companies you need to generate leads from and your freelancer will return a spreadsheet with their contact information.</h3>

<%= render 'form' %>

<!--<%= link_to 'Show', @leadgen %>-->

app/views/leadgens/index.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">

<h1 style="margin:25px 0 60px 0">Generate Leads <span style="float:right"><%= link_to 'New Campaign', new_leadgen_path, class: "button" %><span></h1>

<%= render 'leadgen' %>
<br />
</div>     

app/views/leadgens/new.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">

<h3>Enter the list of companies you need to generate leads from and your freelancer will return a spreadsheet with their contact information.</h3>

<%= render 'form' %>

app/views/leadgens/show.html.erb
<%= render 'layouts/nav_sheets' %>
<div class="content-events">


<div class="contact-card">
<p>
  <strong>Name:</strong>
  <%= @leadgen.title %>
</p>



<p>
  <strong>Companies:</strong>
  <%= @leadgen.companies %>
</p>

<p>
  <strong>Seniority:</strong>
  <%= @leadgen.seniority %>
</p>

<p>
  <strong>Leads per company:</strong>
  <%= @leadgen.leadsper %>
</p>

</div>

<p>
  <strong>Deadline:</strong>
  <%= @leadgen.deadline %>
</p>

<%= link_to 'Edit', edit_leadgen_path(@leadgen) %> | <%= link_to 'Delete', @leadgen, method: :delete, data: { confirm: 'Are you sure?' } %>



<div class="upload-sheets-box">
<%= render 'leadgenupload' %>
</div>

</div>