config/routes.rb
Prospectingzen::Application.routes.draw do

  resources :charges
  
  devise_for :users

  devise_scope :user do
  authenticated :user do
    root 'pages#home', as: :authenticated_root
    get 'feedback' => 'pages#feedback'
    get 'referrals' => 'pages#referrals'
    get 'landing' => 'pages#landing'
    resources :events, :contacts, :leadgens
    get 'assistants' => 'pages#assistants'

  end
  unauthenticated do
    root 'devise/sessions#new', as: :unauthenticated_root
  end
end

  

end

app/views/layouts/_header.html.erb
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js"> <!--<![endif]-->
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="https://ssl.gstatic.com/docs/script/css/add-ons.css">
        <!-- Place favicon.ico and apple-touch-icon.png in the root directory -->
        <link href='http://fonts.googleapis.com/css?family=Lato' rel='stylesheet' type='text/css'>
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
        <script>window.jQuery || document.write('<script src="js/vendor/jquery-1.10.2.min.js"><\/script>')</script>
    <!-- SHEETS STYLES & JS DEPENDENCIES -->
        <script src="https://code.jquery.com/jquery-1.11.1.min.js"></script>
        <script src="http://handsontable.com/dist/handsontable.full.js"></script>
        <script src="http://handsontable.com/lib/jquery-ui/js/jquery-ui.custom.min.js"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
    <link rel="shortcut icon" href="http://media.smashingmagazine.com/images/favicon/thinkpink.gif" />
    </head>

app/views/layouts/_loginheader.html.erb
<% if user_signed_in? %>
          <%else %>
<div class="login-container">
<img src="http://ryanfsalerno.com/hosting/imgs/squarelogo.png" class="login-img">
</div>

<div class="bottom-link"><div class="signupnow">Don't have an account? <a href="http://prospectingzen.co"><strong>Register today</strong></a>.</div></div>          
          <% end %>

app/views/layouts/_nav_sheets.html.erb
<nav>
    <a href="/"><div class="logo"><img src="http://ryanfsalerno.com/hosting/imgs/squarelogo.png" class="logo-img"></div><a/>

<ul class="leftnav">
    <li class="leftnav"><a href="/">New Assignment</a></li>
    <li class="leftnav"><%= link_to "Assistant Center", assistants_path %></li>
</ul>
            <div>
<div class="addnew">
    <!--<span>Add new</span><span class="plus-icon"></span>-->
    <span>My Assignments</span><!--<span class="glyphicon glyphicon-plus"></span>-->
    <div class="nav-divider"></div>
</div>
 <ul class="leftnav">
    <li class="leftnav"><%= link_to "Lead Generation", leadgens_path %></li>
    <li class="leftnav"><%= link_to "My Events", events_path %></li>
    <li class="leftnav"><%= link_to "VIP Contacts", contacts_path %></li>
    
    <!--<li><a href="#4">Sheet 4</a></li>
    <li><a href="#5">Sheet 5</a></li>
    <li><a href="#6">Sheet 6</a></li>
    <li><a href="sheets_demo.html">Presidents</a></li>-->
</ul> 
</div>
<!--<ul>
  <li><a href="index.html">Dashboard</a></li>
  <li><a href="sheets.html" class="active-nav">Spreadsheets</a></li>
  <li><a href="messenger.html">Messages<span class="alert">22</span></a></li>
  <li><a href="#">Feedback</a></li>
</ul>-->
</nav>

<div class="mycontainer">
    <header>
    <div class="page-title">
        <h1>Let's close deals.</h1>
    </div>

    <div class="top-nav">

<!--<a href="#" class="gear-icon">&nbsp;&nbsp;&nbsp;&nbsp;</a> -->
      <ul class="nav navbar-nav" >
            <li><%= link_to "Feedback", feedback_path, {:style => 'margin-right:20px'} %></li>
    <li><%= link_to "Referrals", referrals_path, {:style => 'margin-right:10px'} %></li>
        <li >
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><%= "#{current_user.name}" %> <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>



      <!-- margin-right feedback 20, referrals 10 -->
    </div>
    </header>

app/views/layouts/_nav_static_pages.html.erb
<nav>
    <div class="logo"><img src="assets/squarelogo.png" class="logo-img"></div>

<ul>
    <li><a href="#">Spreadsheets</a></li>
    <li><a href="#">Assistants</a></li>
</ul>
<!--<ul>
  <li><a href="index.html">Dashboard</a></li>
  <li><a href="sheets.html" class="active-nav">Spreadsheets</a></li>
  <li><a href="messenger.html">Messages<span class="alert">22</span></a></li>
  <li><a href="#">Feedback</a></li>
</ul>-->
</nav>

<div class="mycontainer">
    <header>
    <div class="page-title">
        <h1>Set the Static page header variable here</h1>
    </div>

    <div class="top-nav">
      <!-- margin-right feedback 20, referrals 10 -->
        <%= link_to "Feedback", feedback_path, {:style => 'margin-right:20px'} %>
        <%= link_to "Referrals", referrals_path, {:style => 'margin-right:10px'} %>
        <a href="#" class="gear-icon">&nbsp;&nbsp;&nbsp;&nbsp;</a> 
    </div>
    </header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= render 'layouts/header' %>
		
<body>

<% flash.each do |name, msg| %>
                <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
            <% end %>

<%= yield %>

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-59560933-2', 'auto');
  ga('send', 'pageview');

</script>
</body>
</html>